import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Profil from '../components/Profil'
import Projects from '../components/Projects'

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />

      <section id="profil" className="snap-center ">
        <Profil />
      </section>

      <section id="about" className="snap-center">
        <About />
      </section>

     
      
      <section id="Projects" className="snap-center">
        <Projects />
      </section>
      
      <section id="Contact" className="snap-start">
        <Contact />
      </section>
      
      
    </div>
  )
}

export default Home
